//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPSIT.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorData
    {
        public int Id { get; set; }
        public int HiveId { get; set; }
        public int Temperature { get; set; }
        public int Humidity { get; set; }
        public int Light { get; set; }
        public double Weight { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Hive Hive { get; set; }
    }
}
